title: "Nitish Bhardwaj"
name: "Nitish Bhardwaj"
email: "nitish.bhardwaj11@gmail.com"
  
twitter_username: "nitishpietist"
github_username:  "nitish11"

# Build settings
markdown: "kramdown"
permalink: "/blog/:year/:month/:day/:title"

